const { ALPN_ENABLED } = require("constants");

const discordToken = 'NzI3NjA4MzA2NTQ1MTk3MTA3.XvuUCg.7GulknncsMapUxo1HkLbkIaeFKU';
const publicKey = "1cdddf92e13d51ec7a1031e380b4909206807f2b6afad54108798237d8acf98b";
const applicationId = "727608306545197107";

const prefix = '/';
const commands = [
    'stop',
    'clear'
];

const forbiddenWords = [
    "bum",
    "butt",
    "buttplug",
    "clitoris",
    "cock",
    "coon",
    "crap",
    "cunt",
    "damn",
    "dick",
    "dildo",
    "dyke",
    "fag",
    "feck",
    "fellate",
    "fellatio",
    "felching",
    "fuck",
    "f u c k",
    "fudgepacker",
    "fudge packer",
    "flange",
    "homo",
    "jerk",
    "jizz",
    "knobend",
    "knob end",
    "labia",
    "lmao",
    "lmfao",
    "muff",
    "nigger",
    "nigga",
    "penis",
    "piss",
    "poop",
    "prick",
    "pube",
    "pussy",
    "queer",
    "scrotum",
    "sex",
    "shit",
    "s hit",
    "sh1t",
    "slut",
    "smegma",
    "spunk",
    "tit",
    "tosser",
    "turd",
    "twat",
    "vagina",
    "wank",
    "whore",
    "338/5000",
    "Penner",
    "Arsch",
    "Klitoris",
    "Schwanz",
    "Waschbär",
    "Mist",
    "Fotze",
    "Verdammt",
    "Schwanz",
    "Dildo",
    "Deich",
    "Kippe",
    "feck",
    "Fellate",
    "Fellatio",
    "felchen",
    "Scheiße",
    "Scheiße",
    "Fudgepacker",
    "Flansch",
    "Homo",
    "Trottel",
    "Sperma",
    "Schamlippen",
    "lmao",
    "lmfao",
    "Muff",
    "Nigger",
    "Nigga",
    "Penis",
    "Pisser",
    "Poop",
    "Stechen",
    "pube",
    "Muschi",
    "queer",
    "Hodensack",
    "Sex",
    "Scheisse",
    "Scheiße",
    "sche1se",
    "Schlampe",
    "Smegma",
    "Sperma",
    "titten",
    "Titte",
    "werfen",
    "Scheißer",
    "Möse",
    "Vagina",
    "wichsen",
    "wichser",
    "Hure",
    "scheiss",
    "scheiß",
    "fick"
];


module.exports = { token: discordToken, prefix: prefix, commandArray: commands, forbiddenWords: forbiddenWords, publicKey: publicKey, applicationId: applicationId };